name: CI

on:
  push:
    branches: [ master, main, java-11-jakarta ]
  pull_request:
    branches: [ master, main, java-11-jakarta ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout pcehr-compiled-wsdl-java
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/pcehr-compiled-wsdl-java
          ref: java-11-jakarta
          path: pcehr-compiled-wsdl-java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven
      - name: Install pcehr-compiled-wsdl
        working-directory: pcehr-compiled-wsdl-java
        run: mvn -B "-Dgpg.skip=true" clean install
      - name: Maven verify (default)
        run: mvn -B "-Dgpg.skip=true" clean verify

  wsimport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout pcehr-compiled-wsdl-java
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/pcehr-compiled-wsdl-java
          ref: java-11-jakarta
          path: pcehr-compiled-wsdl-java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven
      - name: Install pcehr-compiled-wsdl
        working-directory: pcehr-compiled-wsdl-java
        run: mvn -B "-Dgpg.skip=true" clean install
      - name: Maven verify (-Pwsimport)
        run: mvn -B "-Dgpg.skip=true" -Pwsimport clean verify
